ren collect.scala.scala collect.scala
ren dfways.scala.scala dfways.scala
ren distinct.scala.scala distinct.scala
ren drop.scala.scala drop.scala
ren groupby.scala.scala groupby.scala
ren join.scala.scala join.scala
ren mapflatmap.scala.scala mapflatmap.scala
ren PartitionerPersonal.scala.scala PartitionerPersonal.scala
ren PartitionerTwoParts.scala.scala PartitionerTwoParts.scala
ren readcsvdf.scala.scala readcsvdf.scala
ren readjsondf.scala.scala readjsondf.scala
ren readparquetdf.scala.scala readparquetdf.scala
ren selectcols.scala.scala selectcols.scala
ren show.scala.scala show.scala
ren sortorderby.scala.scala sortorderby.scala
ren sparksql_aggregates.scala.scala sparksql_aggregates.scala
ren sparksql_bucketing.scala.scala sparksql_bucketing.scala
ren sparksql_first.scala.scala sparksql_first.scala
ren structtype.scala.scala structtype.scala
ren udf.scala.scala udf.scala
ren union.scala.scala union.scala
ren unstructured.scala.scala unstructured.scala
ren wherefilter.scala.scala wherefilter.scala
ren withColumn.scala.scala withColumn.scala
